name: vote-proof-formats-v1-3

on:
  push:
    paths:
      - "ucc/src/ucc/proof_formats.py"
      - "ucc/src/ucc/snark_backend.py"
      - "ucc/tests/test_proof_formats_v1_3.py"
      - ".github/workflows/vote_proof_formats_v1_3.yml"
  pull_request:
    paths:
      - "ucc/src/ucc/proof_formats.py"
      - "ucc/src/ucc/snark_backend.py"
      - "ucc/tests/test_proof_formats_v1_3.py"
      - ".github/workflows/vote_proof_formats_v1_3.yml"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -e "ucc[dev]"
      - name: Run proof format tests
        run: |
          python -m pytest -q ucc/tests/test_proof_formats_v1_3.py
