param(
  [string]$ApprovedProposalFile = "",
  [string]$RunDir = ".\out\telemetry_smoke"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repo = (Resolve-Path "$PSScriptRoot\..").Path
Set-Location $repo

$PY = ".\.venv\Scripts\python.exe"
if (!(Test-Path $PY)) { Write-Host "Missing venv python: $PY" -ForegroundColor Red; exit 1 }

$approvedDir = ".\governance\proposals\approved"
New-Item -Force -ItemType Directory $approvedDir | Out-Null

# Auto-select newest approved proposal if not provided
if ([string]::IsNullOrWhiteSpace($ApprovedProposalFile)) {
  $latest = Get-ChildItem -Path $approvedDir -Filter *.json -File |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1

  if ($null -eq $latest) {
    Write-Host "No approved proposal found in $approvedDir" -ForegroundColor Red
    Write-Host "Tip: ingest a proposal into approved first." -ForegroundColor Yellow
    exit 1
  }

  $ApprovedProposalFile = $latest.FullName
  Write-Host "Auto-selected newest approved proposal:" -ForegroundColor Cyan
  Write-Host "  $ApprovedProposalFile" -ForegroundColor Cyan
} else {
  # Resolve to full path if relative
  if (!(Test-Path $ApprovedProposalFile)) {
    Write-Host "Missing approved proposal: $ApprovedProposalFile" -ForegroundColor Red
    exit 1
  }
  $ApprovedProposalFile = (Resolve-Path $ApprovedProposalFile).Path
  Write-Host "Using provided approved proposal:" -ForegroundColor Cyan
  Write-Host "  $ApprovedProposalFile" -ForegroundColor Cyan
}

# Ensure output folders exist
New-Item -Force -ItemType Directory .\governance\implementation\receipts | Out-Null
New-Item -Force -ItemType Directory .\governance\implementation\rollback | Out-Null

# Timestamp
$stamp = (Get-Date).ToUniversalTime().ToString("yyyyMMdd_HHmmssZ")

# Receipt/Rollback paths
$receipt = ".\governance\implementation\receipts\$stamp`__receipt.json"
$rollback = ".\governance\implementation\rollback\$stamp`__rollback.json"

# Proposal sha256
$propSha = (& $PY -c "import hashlib; p=open(r'$ApprovedProposalFile','rb').read(); print(hashlib.sha256(p).hexdigest())").Trim()

# Git file list (working tree diff)
$files = @(git diff --name-only | Where-Object { $_ -ne "" })
if ($files.Count -eq 0) {
  # if clean, include at least something so schema minItems passes
  $files = @("NO_DIFF_DETECTED")
}

# Telemetry after snapshot (if present)
$after = @{}
if (Test-Path "$RunDir\telemetry.json") {
  try {
    $after = (Get-Content "$RunDir\telemetry.json" -Raw | ConvertFrom-Json).metrics
  } catch { $after = @{} }
}

# Rollback plan template
@"
{
  `"schema_id`": `"coherencelattice.rollback_plan.v1`",
  `"version`": 1,
  `"created_at`": `"$(Get-Date -Format o)`",
  `"trigger_conditions`": [
    `"CI fails after merge`",
    `"telemetry_ok false`",
    `"Es drops below 0.80`",
    `"Lambda rises above 0.20`"
  ],
  `"rollback_steps`": [
    `"git revert <merge_commit_sha>`",
    `"rerun CI`",
    `"rerun telemetry smoke and confirm baselines`"
  ],
  `"notes`": `"Fill in commit SHA after PR merge.`"
}
"@ | Set-Content $rollback -Encoding UTF8

# Receipt template
$filesJson = ($files | ConvertTo-Json)
@"
{
  `"schema_id`": `"coherencelattice.implementation_receipt.v1`",
  `"version`": 1,
  `"created_at`": `"$(Get-Date -Format o)`",
  `"proposal_path`": `"$ApprovedProposalFile`",
  `"proposal_sha256`": `"$propSha`",
  `"summary`": `"IMPLEMENTATION SUMMARY: fill this in.`",
  `"files_changed`": $filesJson,
  `"tests`": {
    `"ucc`": `"pytest -q ucc/tests`",
    `"python`": `"pytest -q python/tests`"
  },
  `"telemetry_delta`": {
    `"before`": {},
    `"after`": $(ConvertTo-Json $after)
  },
  `"rollback_plan_path`": `"$rollback`",
  `"notes`": `"Receipt generated by scripts/new_receipt.ps1. Fill summary and update telemetry_delta.before if desired.`"
}
"@ | Set-Content $receipt -Encoding UTF8

Write-Host "Created receipt: $receipt" -ForegroundColor Green
Write-Host "Created rollback: $rollback" -ForegroundColor Green
Write-Host "Next: validate and commit these files with your PR." -ForegroundColor Yellow

