param(
  [string]$ApprovedProposalFile = "",
  [string]$RunDir = ".\out\telemetry_smoke"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repo = (Resolve-Path "$PSScriptRoot\..").Path
Set-Location $repo

$PY = ".\.venv\Scripts\python.exe"
if (!(Test-Path $PY)) { Write-Host "Missing venv python: $PY" -ForegroundColor Red; exit 1 }

$approvedDir = ".\governance\proposals\approved"
New-Item -Force -ItemType Directory $approvedDir | Out-Null

# Auto-select newest approved proposal
if ([string]::IsNullOrWhiteSpace($ApprovedProposalFile)) {
  $latest = Get-ChildItem -Path $approvedDir -Filter *.json -File |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
  if ($null -eq $latest) {
    Write-Host "No approved proposal found in $approvedDir" -ForegroundColor Red
    exit 1
  }
  $ApprovedProposalFile = $latest.FullName
  Write-Host "Auto-selected approved proposal:" -ForegroundColor Cyan
  Write-Host "  $ApprovedProposalFile" -ForegroundColor Cyan
} else {
  if (!(Test-Path $ApprovedProposalFile)) {
    Write-Host "Missing approved proposal: $ApprovedProposalFile" -ForegroundColor Red
    exit 1
  }
  $ApprovedProposalFile = (Resolve-Path $ApprovedProposalFile).Path
}

# Ensure dirs
New-Item -Force -ItemType Directory .\governance\implementation\receipts | Out-Null
New-Item -Force -ItemType Directory .\governance\implementation\rollback | Out-Null

$stamp = (Get-Date).ToUniversalTime().ToString("yyyyMMdd_HHmmssZ")
$receiptPath  = ".\governance\implementation\receipts\$stamp`__receipt.json"
$rollbackPath = ".\governance\implementation\rollback\$stamp`__rollback.json"

# Hash proposal (lowercase)
$propSha = (Get-FileHash -Algorithm SHA256 -Path $ApprovedProposalFile).Hash.ToLower()

# Files changed (working tree diff)
$files = @(git diff --name-only | Where-Object { $_ -ne "" })
if ($files.Count -eq 0) { $files = @("NO_DIFF_DETECTED") }

# Telemetry metrics (after)
$after = @{}
$telPath = Join-Path $RunDir "telemetry.json"
if (Test-Path $telPath) {
  try { $after = (Get-Content $telPath -Raw | ConvertFrom-Json).metrics } catch { $after = @{} }
}

# JSON-safe path strings (forward slashes)
$proposalPathJson = ($ApprovedProposalFile -replace "\\","/")
$rollbackPathJson = ($rollbackPath -replace "\\","/")

# Rollback plan object
$rollback = [pscustomobject]@{
  schema_id = "coherencelattice.rollback_plan.v1"
  version = 1
  created_at = (Get-Date).ToUniversalTime().ToString("o")
  trigger_conditions = @(
    "CI fails after merge",
    "telemetry_ok false",
    "Es drops below 0.80",
    "Lambda rises above 0.20"
  )
  rollback_steps = @(
    "git revert <merge_commit_sha>",
    "rerun CI",
    "rerun telemetry smoke and confirm baselines"
  )
  notes = "Fill in commit SHA after PR merge."
}

# Receipt object
$receipt = [pscustomobject]@{
  schema_id = "coherencelattice.implementation_receipt.v1"
  version = 1
  created_at = (Get-Date).ToUniversalTime().ToString("o")
  proposal_path = $proposalPathJson
  proposal_sha256 = $propSha
  summary = "IMPLEMENTATION SUMMARY: fill this in."
  files_changed = $files
  tests = [pscustomobject]@{
    ucc = "pytest -q ucc/tests"
    python = "pytest -q python/tests"
  }
  telemetry_delta = [pscustomobject]@{
    before = [pscustomobject]@{}
    after = $after
  }
  rollback_plan_path = $rollbackPathJson
  notes = "Receipt generated by scripts/new_receipt.ps1 (JSON-safe)."
}

# Write both
($rollback | ConvertTo-Json -Depth 30) | Set-Content -Path $rollbackPath -Encoding UTF8
($receipt  | ConvertTo-Json -Depth 30) | Set-Content -Path $receiptPath  -Encoding UTF8

Write-Host "Created receipt: $receiptPath" -ForegroundColor Green
Write-Host "Created rollback: $rollbackPath" -ForegroundColor Green
Write-Host "Next: validate and commit these with your PR." -ForegroundColor Yellow
